version: "3.9" 

services:
  # api:
  #   image: api
  #   environment:
  #     - MONGO_URI=mongodb://admin:password@mongodb:27017/
  #     - MONGO_DATABASE=mydb
  #     - REDIS_URI=redis:6379
  #   networks:
  #     - api_network
  #   external_links:
  #     - mongodb
  #     - redis
  #   scale: 5

  redis:
    image: redis
    networks:
      - api_network
    ports:
      - 6379:6379

  mongodb:
    image: mongo:4.4.3
    networks:
      - api_network
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

networks:
  api_network: